import type { Metadata } from "next";
import "./globals.css";
import Header from "./src/component/Header";

export const metadata: Metadata = {
  title: "GABE PRODUÇÃO AUDIOVISUAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}